[workspace]
authors = ["ehsanmok <ehsanmok@users.noreply.github.com>"]
channels = ["https://conda.modular.com/max-nightly", "conda-forge"]
name = "sierpinsky"
platforms = ["linux-64"]
version = "0.0.0"

[feature.cuda]
system-requirements = { cuda = "12.0" }

[feature.rocm]
system-requirements = {}

[tasks]
sierpinsky = "mojo sierpinsky.mojo"

[dependencies]
max = "*"

[environments]
cuda = { features = ["cuda"] }
rocm = { features = ["rocm"] }
default = { features = ["cuda"] }
