[workspace]
name = "pixi-crispy-doom"
authors = ["Bas Zalmstra <zalmstra.bas@gmail.com>"]
channels = ["https://prefix.dev/conda-forge"]
platforms = ["win-64", "linux-64", "osx-arm64", "osx-64"]
preview = ["pixi-build"]

#
# Define an environment which installs the root package
#

[dependencies]
crispy-doom = { path = "." }

[tasks.start]
cmd = "crispy-doom -iwad freedoom-0.13.0/freedoom1.wad"
description = "Start the crispy-doom executable from our locally built package."
depends-on = ["module", "get-iwad"]

#
# The prep environment is used to prepare the build environment.
#

[feature.prep.dependencies]
python = ">=3.13"

[feature.prep.tasks.module]
cmd = "git submodule update --init --recursive"
description = "Download and initialize the submodules"
outputs = ["src/README.md"]

[feature.prep.tasks.get-iwad]
cmd = "python get_freedoom_iwad.py"
description = "Download and extract Freedoom IWADs"
outputs = ["freedoom1.wad","freedoom2.wad","freedm.wad", ]

[environments]
prep = { features = ["prep"], no-default-feature = true }

#
# This section defines the package crispy-doom from the root of the repository.
#

[package]
name = "crispy-doom"
version = "6.0.0"
license = "GPL-2.0"

# Use the CMake build backend which will automatically build the CMakeLists.txt
# next to our pixi.toml
[package.build]
backend = { name = "pixi-build-cmake", version = "0.1.*" }
channels = [
    "https://prefix.dev/pixi-build-backends",
    "https://prefix.dev/conda-forge"
]

# Define the dependencies we need on our host machine
[package.build-dependencies]
cmake = "~=3.26.4"
ninja = "~=1.11.1"

# Define the dependencies we need for our target platform, e.g. libraries to link
# against.
[package.host-dependencies]
sdl2 = "~=2.26.5"
sdl2_mixer = "~=2.6.3"
sdl2_net = "~=2.2.0"
libpng = "~=1.6.39"
zlib = "~=1.3.1"
